apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: database-backup-cronjob
  namespace: fpsa
spec:
  schedule: 0 1 * * *
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: "docker.pkg.github.com/federation-purple-study-associations/fpsa-cron-database-backup/cronjob:latest"
            name: database-backup
            env:
            - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: db
                    key: DB_HOST
            - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: db
                    key: DB_USER
            - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db
                    key: DB_PASSWORD
            - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: db
                    key: DB_NAME
